pages:
  csl-ui:
    baseUrl: ${CSL_UI_BASE_URL:http://localhost:3001}
    modules:
      baseUrl: ${CONTENT_CDN_BASE_URL}
      video:
        load-timeout: ${VIDEO_MODULE_LOAD_TIMEOUT_MS:3000}
      file:
        load-timeout: ${FILE_MODULE_LOAD_TIMEOUT_MS:1000}
      elearning:
        load-timeout: ${ELEARNING_MODULE_LOAD_TIMEOUT_MS:3000}
  csl-management:
    baseUrl: ${CSL_MANAGEMENT_BASE_URL:http://localhost:3005}
    module-creation:
      pdf-file-name: ${SAMPLE_FILE_LOCATION:dummy.pdf}
      cdn-pdf:
        url: ${SAMPLE_FILE_CDN_LOCATION:}
        name: dummy
      elearning:
        url: ${SAMPLE_ELEARNING_CDN_LOCATION:}
        startPage: ${SAMPLE_ELEARNING_CDN_START_PAGE:index.htm}
      cdn-video:
        url: ${SAMPLE_VIDEO_CDN_LOCATION:}
  identity:
    baseUrl: ${IDENTITY_BASE_URL:http://localhost:8080}
browser: Chrome
users:
  learner:
    email: ${LEARNER_EMAIL:learner@domain.com}
    password: ${LEARNER_PASSWORD:test}
  admin:
    email: ${ADMIN_EMAIL:super-admin@domain.com}
    password: ${ADMIN_PASSWORD:test&BxV}
api:
  elasticsearch:
    baseUrl: ${ELASTIC_URL:http://localhost:9200}
    username: ${ELASTIC_USERNAME:elastic}
    password: ${ELASTIC_PASSWORD:changeme}
db:
  learner-record:
    connection-string: ${LEARNER_RECORD_DB:jdbc:mysql://localhost:3306/learner_record?user=root&password=my-secret-pw&useSSL=false}
  identity:
    connection-string: ${IDENTITY_RECORD_DB:jdbc:mysql://localhost:3306/identity?user=root&password=my-secret-pw&useSSL=false}
    user-password: ${GENERIC_USER_PASSWORD:test}
  csrs:
    connection-string: ${CSRS_DB:jdbc:mysql://localhost:3306/csrs?user=root&password=my-secret-pw&useSSL=false}
  mongo:
    connection-string: ${MONGO_DB:mongodb://localhost:27017}
report:
  dir: ${REPORT_DIR:report}
