package uk.gov.cslearning.acceptanceTests.Data;

import org.apache.commons.lang3.RandomStringUtils;
import uk.gov.cslearning.acceptanceTests.API.CourseDB.model.Course;
import uk.gov.cslearning.acceptanceTests.API.CourseDB.model.LearningProvider;
import uk.gov.cslearning.acceptanceTests.API.CourseDB.model.Owner;

import java.util.ArrayList;

public class CourseData {

    public static Course genericCourse() {
        String randomID = RandomStringUtils.randomAlphabetic(4);
        String courseID = String.format("ACCEPTANCE-COURSE-%s", randomID);
        return new Course(
                courseID,
                String.format("ACC: Generic Course %s", courseID),
                "A generic course generated by acceptance tests",
                "Long description for a generic acceptance test course",
                "Learning outcomes for a generic acceptance test course",
                new ArrayList<>(),
                new LearningProvider("M9yc7qKKT1is7tH98SbEpw", "", new ArrayList<>(), new ArrayList<>()),
                new ArrayList<>(),
                "Preparation for generic course",
                new Owner("GLOBAL", "10211", 19, ""),
                "PUBLIC",
                "Published",
                "TOPIC001"
        );
    }
}
